version: "{build}"

skip_tags: true
test: off
max_jobs: 1

install:
  - cmd: FOR /F "delims=" %%a IN ('python appveyor_mingw.py') DO SET MINGW_DIR=%%a
  - cmd: IF "."=="%MINGW_DIR%" ( EXIT 404 )
  - cmd: SET PATH=%MINGW_DIR%\mingw64\bin;%PATH%

before_build:
  - cmd: mingw32-make --version | head -1
  - cmd: g++ --version | head -1
  - cmd: 7z --help | head -3

build_script:
  - cmd: mingw32-make -j1 --keep-going

deploy: off
