version: "{build}"

skip_tags: true
test: off
max_jobs: 1

build_script:
  - cmd: python test.py
  - cmd: which make
  - cmd: which mingw32-make
  - cmd: mingw32-make --version | head -1
  - cmd: g++ --version | head -1
  - cmd: 7z --help | head -3

deploy: off
