version: "{build}"

skip_tags: true
test: off
max_jobs: 1

build_script:
  - cmd: echo %MINGW_DIR%
  - cmd: for /f "delims=" %%a in ('python appveyor_mingw.py') do set MINGW_DIR=%%a
  - cmd: echo %MINGW_DIR%

deploy: off
